spring:
  application:
    name: Proyecto-integrador

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      format-sql: true